### ISSUE TITLE
Grab 'Ginny' content from old repo?

### ISSUE THREAD

**Issue by zddguu** [slavetrainermod/WT-Silver#21] opened 2018-06-21 18:01 UTC
I'm not sure if you were aware, but @ShanksAkagami was working on Ginny content as a fork from the last repo.
There hasn't been a commit from him for 4+ months, so he probably gave up, but looks like he made some significant headway in the month he worked on it. I haven't played his build to see the quality, but might be worthwhile taking a look.

https://github.com/stg-trainer-annon/BT-Silver-Base/compare/master...ShanksAkagami:Ginny_init

**Comment by CatgirlsRLove** [comment] 2018-06-22 03:35
A brief lookthrough doesn't show many events actually written (around 5 or so) but the graphical assets could potentially be useful. I'm messing around with it on my own at the moment just to see how hard it would be to make the stuff there work with my very limited knowledge of Ren'py.

**Comment by asease1** [comment] 2018-09-10 19:00
Going to close this one since it not a bug and mo and Merlin want to focus on the other girls if you want to try to add heir make a pull request but don't just steal his stuff ask him if it okay to use if you want to use his code and art^^

**Closed by asease1** 2018-09-10 19:00 UTC
